
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracking-backend
    ports:
      - "8000:8000"
    env_file:
      - .env  
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    depends_on:
      - db

  tracker-server:
    build:
      context: ./tracker_server  
      dockerfile: Dockerfile
    container_name: tracking-tcp-server
    ports:
      - "5023:5023"  
    env_file:
      - .env  
    environment:
      - TRACKER_HOST=${TRACKER_HOST}
      - TRACKER_PORT=${TRACKER_PORT}
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - web
      - db

  db:
    image: postgres:15
    container_name: tracking-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  ngrok-backend:
    image: ngrok/ngrok
    container_name: ngrok-backend
    ports:
      - "4040:4040"  
    command: http web:8000
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=2xhFtRPBng3PFBMBwVaY6i2E6ye_619QwYtPCgjA4iUULhMg1

volumes:
  postgres_data: