app = "sistema-tracking-tcp"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 5023
  protocol = "tcp"

  [[services.ports]]
    port = 5023       
    handlers = []

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
